---
- name: install nginx
  hosts: all
  tasks: 
  - name: Install Nginx on ubuntu
    apt:
      name: nginx
      state: present
    when: ansible_os_family == "ubuntu"  and ansible_distribution_version == "16.04"

  - name: Install Nginx on Linux
    yum:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat" 
